### ISSUE TITLE
Test Notification not working

### ISSUE THREAD

**Issue by ThatRandomTechGuy** [thomasfinch/PriorityHub#23]
Hi! After compiling/installing the latest commit of Priority Hub, I'm noticing that a send test notification does not work. Note that I have Unify as well, so that could be a conflict of some sort.
Here's a video showing the bug:
[ayylmao](sendvid.com/wcn6wrf6)
The same thing also happens when sending a test notification via the notification center.

Any thoughts?

**Comment by thomasfinch** [comment]
This code hasn't been written yet. Please don't open issues for unfinished versions.
